"""ECG risk model scoring interfaces and implementations."""

from ecg_alignment.scoring.base import (
  CABRERA_12_LEADS,
  STANDARD_CLINICAL_12_LEADS,
  BaseEcgModelAdapter,
  BatchInferenceResult,
  CropAlign,
  ImageRenderConfig,
  InputModality,
  ModelOutputResult,
  TransformerAdapterConfig,
  WaveformPadMode,
  WaveformPreprocessConfig,
)
from ecg_alignment.scoring.cards_clip import (
  DEFAULT_CARDS_CLIP_EMBEDDING_DIM,
  DEFAULT_CARDS_CLIP_IMAGE_SIZE,
  DEFAULT_CARDS_CLIP_MODEL_NAME,
  DEFAULT_CARDS_CLIP_REVISION,
  CardsClipAdapter,
  CardsClipConfig,
  compute_centroid_similarity_score,
  cosine_similarity_1d,
  load_cards_clip_model,
)
from ecg_alignment.scoring.dbeta import (
  DEFAULT_DBETA_EMBEDDING_DIM,
  DEFAULT_DBETA_MODEL_NAME,
  DEFAULT_DBETA_REVISION,
  DEFAULT_DBETA_SAMPLING_RATE_HZ,
  DEFAULT_DBETA_SIGNAL_LENGTH,
  DbetaAdapter,
  DbetaConfig,
  load_dbeta_model,
)
from ecg_alignment.scoring.preprocess import (
  pad_or_crop_waveform,
  preprocess_waveform,
  render_12lead_ecg_image,
  resample_waveform,
  scale_waveform_units,
  validate_and_reorder_leads,
)
from ecg_alignment.scoring.traditional import (
  CIISCategory,
  CIISMeasurements,
  CIISScoreResult,
  LeadFeatures,
  classify_ciis_category,
  compute_ciis_from_measurements,
  compute_cornell_voltage,
  compute_sokolow_lyon_voltage,
  extract_lead_features,
  score_ecg_waveform,
  score_simplified_ischemic_ecg,
)

__all__ = [
  "CABRERA_12_LEADS",
  "STANDARD_CLINICAL_12_LEADS",
  "BaseEcgModelAdapter",
  "BatchInferenceResult",
  "CropAlign",
  "ImageRenderConfig",
  "InputModality",
  "ModelOutputResult",
  "TransformerAdapterConfig",
  "WaveformPadMode",
  "WaveformPreprocessConfig",
  "DEFAULT_CARDS_CLIP_EMBEDDING_DIM",
  "DEFAULT_CARDS_CLIP_IMAGE_SIZE",
  "DEFAULT_CARDS_CLIP_MODEL_NAME",
  "DEFAULT_CARDS_CLIP_REVISION",
  "CardsClipAdapter",
  "CardsClipConfig",
  "compute_centroid_similarity_score",
  "cosine_similarity_1d",
  "load_cards_clip_model",
  "DEFAULT_DBETA_EMBEDDING_DIM",
  "DEFAULT_DBETA_MODEL_NAME",
  "DEFAULT_DBETA_REVISION",
  "DEFAULT_DBETA_SAMPLING_RATE_HZ",
  "DEFAULT_DBETA_SIGNAL_LENGTH",
  "DbetaAdapter",
  "DbetaConfig",
  "load_dbeta_model",
  "pad_or_crop_waveform",
  "preprocess_waveform",
  "render_12lead_ecg_image",
  "resample_waveform",
  "scale_waveform_units",
  "validate_and_reorder_leads",
  "CIISCategory",
  "CIISMeasurements",
  "CIISScoreResult",
  "LeadFeatures",
  "classify_ciis_category",
  "compute_ciis_from_measurements",
  "compute_cornell_voltage",
  "compute_sokolow_lyon_voltage",
  "extract_lead_features",
  "score_ecg_waveform",
  "score_simplified_ischemic_ecg",
]


