"""ECG Model Alignment package.

Studies alignment and discordance between traditional ECG-only risk models
and modern multimodal transformer-derived ECG representations.
"""

from ecg_alignment.cohort import (
  CohortStep,
  compute_age_at_ecg,
  compute_linkage_statistics,
  filter_adult_records,
  generate_cohort_flow,
  link_records_to_admissions,
  select_index_ecgs,
)
from ecg_alignment.data import (
  CANONICAL_12_LEADS,
  DEFAULT_DURATION_SECONDS,
  DEFAULT_SAMPLING_RATE_HZ,
  DEFAULT_SIGNAL_LENGTH_SAMPLES,
  DataPaths,
  EcgHeaderInfo,
  WaveformEligibilityCriteria,
  load_admissions,
  load_machine_measurements,
  load_patients,
  load_record_list,
  read_ecg_header,
  read_ecg_waveform,
  validate_waveform_eligibility,
)
from ecg_alignment.outcomes import (
  DEFAULT_HORIZONS,
  DEFAULT_HORIZON_1YR,
  DEFAULT_HORIZON_30D,
  DEFAULT_HORIZON_90D,
  FollowUpPolicy,
  OutcomeHorizon,
  compute_inhospital_mortality,
  compute_mortality_outcomes,
  compute_outcome_statistics,
  compute_patient_death_table,
  filter_valid_outcomes,
  generate_outcome_report_markdown,
)
from ecg_alignment.split import (
  DEFAULT_SPLIT_DEV,
  DEFAULT_SPLIT_SEED,
  DEFAULT_SPLIT_TEST,
  DEFAULT_SPLIT_VAL,
  CohortAttritionStep,
  CohortSplitResult,
  SplitRatios,
  assign_patient_disjoint_split,
  build_primary_cohort_and_split,
  compute_split_summary_statistics,
  derive_primary_cohort,
  generate_cohort_flow_markdown,
  save_split_assignments,
  verify_split_disjointness,
)

__version__ = "0.1.0"

__all__ = [
  "__version__",
  "CANONICAL_12_LEADS",
  "DEFAULT_DURATION_SECONDS",
  "DEFAULT_SAMPLING_RATE_HZ",
  "DEFAULT_SIGNAL_LENGTH_SAMPLES",
  "DataPaths",
  "EcgHeaderInfo",
  "WaveformEligibilityCriteria",
  "load_admissions",
  "load_machine_measurements",
  "load_patients",
  "load_record_list",
  "read_ecg_header",
  "read_ecg_waveform",
  "validate_waveform_eligibility",
  "CohortStep",
  "compute_age_at_ecg",
  "compute_linkage_statistics",
  "filter_adult_records",
  "generate_cohort_flow",
  "link_records_to_admissions",
  "select_index_ecgs",
  "DEFAULT_HORIZONS",
  "DEFAULT_HORIZON_1YR",
  "DEFAULT_HORIZON_30D",
  "DEFAULT_HORIZON_90D",
  "FollowUpPolicy",
  "OutcomeHorizon",
  "compute_inhospital_mortality",
  "compute_mortality_outcomes",
  "compute_outcome_statistics",
  "compute_patient_death_table",
  "filter_valid_outcomes",
  "generate_outcome_report_markdown",
  "DEFAULT_SPLIT_DEV",
  "DEFAULT_SPLIT_SEED",
  "DEFAULT_SPLIT_TEST",
  "DEFAULT_SPLIT_VAL",
  "CohortAttritionStep",
  "CohortSplitResult",
  "SplitRatios",
  "assign_patient_disjoint_split",
  "build_primary_cohort_and_split",
  "compute_split_summary_statistics",
  "derive_primary_cohort",
  "generate_cohort_flow_markdown",
  "save_split_assignments",
  "verify_split_disjointness",
]


